### PR TITLE
HMS Calorimeter Calibrations

### PR DESCRIPTION
**Pull request by ab6361**
Please have a look at ELOG 251

### CODE REVIEW

**Comment by ccotton98** [comment]
Settings I found that probably need more statistics (roughly <10k) and/or are missing calibrations (or they are negative, which may actually be ok, I'm not sure) for particular pmts: 2, 3, 18, 33, 34, 38, 39, 41, 45, 46, 47, 51, 52, 54, 55, 57, 58, 59, 66, 67, 76, 78, 79, 88, 96, 98, 99, 104, 105, 106, 108, 113.

This is just from a quick scan, so probably not exhaustive. I did not include runs that had weird gains as long as they were not negative. I would set min evts to calibrate a pmt to something higher than the default, like 100 as I think Dave mentioned during the meeting since we are seeing negative/very different calibration values where it would probably be best to use some default value for these PMTs. In general, try to use a larger run or chain to try to meet these statistics, and if that's not possible then put in some rough default value by hand so there is at least some number there for each PMT.

**Comment by ab6361** [comment]
I took the average gain for each PMT in the last 4 columns of the HMS Calorimeter using the 3 defocused runs. I assigned the average value to the PMTs with missing calibrations. I am not comfortable with changing the negative ones since those values were determined by the script. If that sounds good the, we can go ahead and accept the pull request. Also I couldn’t exactly how I would change the HMS Calorimeter Calibration script to change the minute events from 10, but I feel that can wait while we go ahead with pass-1 replay.

Sincerely,
Abhyuday Sharda

**Comment by ccotton98** [comment]
Following up from our meeting/slack:
1-Now that I think about it, negative calibration constants might be fine. I was thinking that the calibration constant may be  multiplicative like for the Cerenkov which would make negative values unphysical, but looking more closely at the other constants that may not be the case. Can you or someone else confirm this?
2-The minimum number of events required to calibrate a PMT can be set via the corresponding parameter in the input.dat file in the calorimeter calibration directory. My intuition is that ~10 events/pmt is too few to get a reliable calibration, so we would want to increase the minimum to something a bit larger and use some default value when the minimum is not met. I'm not sure exactly what the new minimum should be, at least 20, maybe 50 or 100?
3-Overall, I think ~<10k total events used in the calibration per setting should be avoided in order to get a reasonable calibration in most PMTs. Most settings already exceed that goal by a wide margin, so using a different run/chaining together runs should only be necessary for a handful of settings.
@gaskelld Any thoughts?

**Comment by ab6361** [comment]
I also changed the name of the function for SCRIPTS/HMS/CALIBRATION/replay_calorimeter_hms.C from replay() to replay_calorimeter_hms(). I did this because otherwise the replays fail when submitted in the farm. I’ll make a detailed ELOG entry about all of the changes I made but just wanted to get this out there now so Tyler can get working on pass-1 replay this week.

**Pull request merged**
